[FIX] calendar: Avoiding multi-company access errors when accessing an event
File \"/opt/odoo/auto/addons/calendar/models/res_partner.py\", line 78, in get_attendee_detail
    'is_organizer': 1 if attendee.partner_id == attendee.event_id.user_id.partner_id else 0,
File \"/opt/odoo/custom/src/odoo/odoo/fields.py\", line 3113, in __get__
    return super().__get__(records, owner)
File \"/opt/odoo/custom/src/odoo/odoo/fields.py\", line 1274, in __get__
    recs._fetch_field(self)
File \"/opt/odoo/custom/src/odoo/odoo/models.py\", line 4120, in _fetch_field
    self.fetch(fnames)
File \"/opt/odoo/custom/src/odoo/odoo/models.py\", line 4164, in fetch
    raise self.env['ir.rule']._make_access_error('read', forbidden)
    odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.
    Sorry, user doesn't have read access to: (res.users: xx)

Example use case:
- Create a test company
- Create a test user linked only to the test company (default company = test company)
- Log in with the test user and create a calendar event, adding Mitchell Admin as an attendee
- Log in with Mitchell Admin (with only YourCompany selected) to the calendar

TT62348